spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.142.244.123:8848
        namespace: public
        group: DEFAULT_GROUP
  data:
    redis:
      host: 115.190.125.94
      port: 6379
      password: root
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          min-idle: 2
          max-idle: 10
          max-active: 20

ng:
  security:
    jwt:
      secret: JWDdmm@2552
      access-token-expire-ms: 7200000
      refresh-token-expire-ms: 2592000000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.notegather: INFO
