server:
  port: 8888

spring:
  application:
    name: notegather-gateway
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:notegather-gateway.yaml
      - optional:nacos:common.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:8848
        namespace: dev
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.1.12:8848
        namespace: dev
        username: nacos
        password: nacos
        file-extension: yaml
        shared-configs:
          - data-id: common.yaml
            refresh: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
