-- NoteGather Phase 1 database schema
-- PostgreSQL 16
--
-- Run this script while connected to the application database, for example:
--   psql -U ng -d notegather -f phase1_database.sql
--
-- IDs are generated by the application Snowflake generator and are therefore
-- intentionally not assigned a database default.
-- The deleted column follows MyBatis-Plus logical-delete conventions:
--   0 = active, 1 = logically deleted.

BEGIN;

-- Keep update_time correct for direct SQL writes as well as MyBatis writes.
CREATE OR REPLACE FUNCTION ng_touch_update_time()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ==================== Identity ====================

CREATE TABLE IF NOT EXISTS t_user (
    id          BIGINT PRIMARY KEY,
    username    VARCHAR(64)  NOT NULL,
    password    VARCHAR(256) NOT NULL,
    nickname    VARCHAR(64),
    avatar_url  VARCHAR(512),
    status      SMALLINT     NOT NULL DEFAULT 1,
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT ck_user_username_not_blank CHECK (length(btrim(username)) > 0),
    CONSTRAINT ck_user_password_not_blank CHECK (length(password) > 0),
    CONSTRAINT ck_user_status CHECK (status IN (0, 1)),
    CONSTRAINT ck_user_deleted CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE t_user IS 'Application users; access and refresh tokens are stored in Redis.';

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_username_active
    ON t_user (username)
    WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_user_status
    ON t_user (status, id)
    WHERE deleted = 0;

-- ==================== Knowledge tree ====================

CREATE TABLE IF NOT EXISTS t_library (
    id          BIGINT PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(256) NOT NULL,
    type        VARCHAR(32)  NOT NULL,
    description TEXT,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_library_id_user UNIQUE (id, user_id),
    CONSTRAINT fk_library_user FOREIGN KEY (user_id)
        REFERENCES t_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_library_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_library_type CHECK (type IN ('RESOURCE', 'SCRATCH', 'NOTE', 'DIARY')),
    CONSTRAINT ck_library_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_library_deleted CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE t_library IS 'A user-owned knowledge base.';
COMMENT ON COLUMN t_library.type IS 'Phase 1 values: RESOURCE, SCRATCH, NOTE, DIARY.';

CREATE UNIQUE INDEX IF NOT EXISTS uk_library_user_name_active
    ON t_library (user_id, name)
    WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_library_user_sort
    ON t_library (user_id, sort_order, id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS t_note (
    id           BIGINT PRIMARY KEY,
    library_id   BIGINT       NOT NULL,
    parent_id    BIGINT,
    user_id      BIGINT       NOT NULL,
    node_type    VARCHAR(16)  NOT NULL,
    title        VARCHAR(512) NOT NULL,
    content      TEXT         NOT NULL DEFAULT '',
    note_type    VARCHAR(16),
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    version      INTEGER      NOT NULL DEFAULT 1,
    parse_status VARCHAR(16)  NOT NULL DEFAULT 'NONE',
    create_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_note_id_library UNIQUE (id, library_id),
    CONSTRAINT fk_note_library_user FOREIGN KEY (library_id, user_id)
        REFERENCES t_library (id, user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_note_parent FOREIGN KEY (parent_id, library_id)
        REFERENCES t_note (id, library_id) ON DELETE CASCADE,
    CONSTRAINT ck_note_parent_not_self CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_note_node_type CHECK (node_type IN ('FOLDER', 'NOTE')),
    CONSTRAINT ck_note_type CHECK (
        (node_type = 'FOLDER' AND note_type IS NULL)
        OR (node_type = 'NOTE' AND note_type IN ('NOTE', 'SCRATCH', 'TABLE'))
    ),
    CONSTRAINT ck_note_title_not_blank CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_note_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_note_version CHECK (version > 0),
    CONSTRAINT ck_note_parse_status CHECK (
        parse_status IN ('NONE', 'PENDING', 'PROCESSING', 'DONE', 'FAILED')
    ),
    CONSTRAINT ck_note_deleted CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE t_note IS 'Folder and note nodes in a library tree.';
COMMENT ON COLUMN t_note.content IS 'Serialized editor content; the application owns its document format.';
COMMENT ON COLUMN t_note.parse_status IS 'Indexing state for note content; file parsing state lives in t_file.';

CREATE INDEX IF NOT EXISTS idx_note_library_parent_sort
    ON t_note (library_id, parent_id, sort_order, id)
    WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_note_user
    ON t_note (user_id, id)
    WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_note_parse_status
    ON t_note (parse_status, update_time)
    WHERE deleted = 0 AND node_type = 'NOTE';

CREATE TABLE IF NOT EXISTS t_note_version (
    id          BIGINT PRIMARY KEY,
    note_id     BIGINT       NOT NULL,
    version     INTEGER      NOT NULL,
    title       VARCHAR(512) NOT NULL,
    content     TEXT         NOT NULL DEFAULT '',
    created_by  BIGINT,
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_note_version_number UNIQUE (note_id, version),
    CONSTRAINT fk_note_version_note FOREIGN KEY (note_id)
        REFERENCES t_note (id) ON DELETE CASCADE,
    CONSTRAINT fk_note_version_creator FOREIGN KEY (created_by)
        REFERENCES t_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_note_version_positive CHECK (version > 0),
    CONSTRAINT ck_note_version_title_not_blank CHECK (length(btrim(title)) > 0)
);

COMMENT ON TABLE t_note_version IS 'Immutable note snapshots used by edit history and recycle-bin recovery.';

CREATE INDEX IF NOT EXISTS idx_note_version_note_time
    ON t_note_version (note_id, version DESC);

-- ==================== Object files and parsing ====================

CREATE TABLE IF NOT EXISTS t_file (
    id           BIGINT PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    library_id   BIGINT,
    note_id      BIGINT,
    file_name    VARCHAR(512) NOT NULL,
    file_type    VARCHAR(16)  NOT NULL,
    content_type VARCHAR(128),
    object_key   VARCHAR(512) NOT NULL,
    bucket       VARCHAR(128) NOT NULL DEFAULT 'notegather',
    size         BIGINT       NOT NULL,
    parse_status VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    chunk_count  INTEGER      NOT NULL DEFAULT 0,
    parse_error  TEXT,
    create_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT fk_file_user FOREIGN KEY (user_id)
        REFERENCES t_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_file_library_user FOREIGN KEY (library_id, user_id)
        REFERENCES t_library (id, user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_file_note_library FOREIGN KEY (note_id, library_id)
        REFERENCES t_note (id, library_id) ON DELETE RESTRICT,
    CONSTRAINT uk_file_object UNIQUE (bucket, object_key),
    CONSTRAINT ck_file_name_not_blank CHECK (length(btrim(file_name)) > 0),
    CONSTRAINT ck_file_type CHECK (file_type IN ('PDF', 'TXT', 'MD')),
    CONSTRAINT ck_file_size CHECK (size >= 0),
    CONSTRAINT ck_file_parse_status CHECK (
        parse_status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED')
    ),
    CONSTRAINT ck_file_chunk_count CHECK (chunk_count >= 0),
    CONSTRAINT ck_file_deleted CHECK (deleted IN (0, 1)),
    CONSTRAINT ck_file_library_required_for_note CHECK (
        note_id IS NULL OR library_id IS NOT NULL
    )
);

COMMENT ON TABLE t_file IS 'Uploaded objects stored in MinIO and associated with a knowledge library or note.';
COMMENT ON COLUMN t_file.object_key IS 'Stable MinIO object key; it is never reused by the database.';
COMMENT ON COLUMN t_file.file_type IS 'Phase 1 upload formats: PDF, TXT and MD.';

CREATE INDEX IF NOT EXISTS idx_file_user_library
    ON t_file (user_id, library_id, update_time DESC)
    WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_file_note
    ON t_file (note_id, id)
    WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_file_parse_status
    ON t_file (parse_status, update_time)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS t_parse_task (
    id             BIGINT PRIMARY KEY,
    file_id        BIGINT       NOT NULL,
    requested_by   BIGINT,
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempt_count  INTEGER      NOT NULL DEFAULT 0,
    chunk_count    INTEGER      NOT NULL DEFAULT 0,
    error_msg      TEXT,
    started_at     TIMESTAMP(3),
    finished_at    TIMESTAMP(3),
    create_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted        SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT fk_parse_task_file FOREIGN KEY (file_id)
        REFERENCES t_file (id) ON DELETE CASCADE,
    CONSTRAINT fk_parse_task_requester FOREIGN KEY (requested_by)
        REFERENCES t_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_parse_task_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED')
    ),
    CONSTRAINT ck_parse_task_attempts CHECK (attempt_count >= 0),
    CONSTRAINT ck_parse_task_chunks CHECK (chunk_count >= 0),
    CONSTRAINT ck_parse_task_times CHECK (
        finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at
    ),
    CONSTRAINT ck_parse_task_deleted CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE t_parse_task IS 'Parse execution history; t_file stores only the current aggregate status.';

CREATE INDEX IF NOT EXISTS idx_parse_task_file_time
    ON t_parse_task (file_id, create_time DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_parse_task_active_file
    ON t_parse_task (file_id)
    WHERE deleted = 0 AND status IN ('PENDING', 'PROCESSING');

-- ==================== RAG chat history ====================

CREATE TABLE IF NOT EXISTS t_chat_session (
    id          BIGINT PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    title       VARCHAR(256),
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT fk_chat_session_user FOREIGN KEY (user_id)
        REFERENCES t_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_chat_session_title CHECK (
        title IS NULL OR length(btrim(title)) > 0
    ),
    CONSTRAINT ck_chat_session_deleted CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE t_chat_session IS 'User-owned RAG conversation sessions.';

CREATE INDEX IF NOT EXISTS idx_chat_session_user_time
    ON t_chat_session (user_id, update_time DESC, id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS t_chat_message (
    id          BIGINT PRIMARY KEY,
    session_id  BIGINT       NOT NULL,
    message_no  INTEGER      NOT NULL,
    role        VARCHAR(16)  NOT NULL,
    content     TEXT         NOT NULL DEFAULT '',
    status      VARCHAR(16)  NOT NULL DEFAULT 'COMPLETED',
    error_msg   TEXT,
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_chat_message_number UNIQUE (session_id, message_no),
    CONSTRAINT fk_chat_message_session FOREIGN KEY (session_id)
        REFERENCES t_chat_session (id) ON DELETE CASCADE,
    CONSTRAINT ck_chat_message_number CHECK (message_no > 0),
    CONSTRAINT ck_chat_message_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM')),
    CONSTRAINT ck_chat_message_status CHECK (
        status IN ('STREAMING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_chat_message_deleted CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE t_chat_message IS 'Persisted user questions and streamed assistant answers.';

CREATE INDEX IF NOT EXISTS idx_chat_message_session_number
    ON t_chat_message (session_id, message_no)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS t_chat_citation (
    id             BIGINT PRIMARY KEY,
    message_id     BIGINT       NOT NULL,
    note_id        BIGINT,
    citation_order INTEGER      NOT NULL,
    note_title     VARCHAR(512) NOT NULL,
    chunk_text     TEXT         NOT NULL,
    score          REAL,
    create_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_chat_citation_order UNIQUE (message_id, citation_order),
    CONSTRAINT fk_chat_citation_message FOREIGN KEY (message_id)
        REFERENCES t_chat_message (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_citation_note FOREIGN KEY (note_id)
        REFERENCES t_note (id) ON DELETE SET NULL,
    CONSTRAINT ck_chat_citation_order CHECK (citation_order >= 0),
    CONSTRAINT ck_chat_citation_title CHECK (length(btrim(note_title)) > 0),
    CONSTRAINT ck_chat_citation_text CHECK (length(chunk_text) > 0)
);

COMMENT ON TABLE t_chat_citation IS 'Citation snapshots returned with the final RAG answer.';
COMMENT ON COLUMN t_chat_citation.note_title IS 'Snapshot kept so historical answers remain readable after a rename.';

CREATE INDEX IF NOT EXISTS idx_chat_citation_message_order
    ON t_chat_citation (message_id, citation_order);

CREATE INDEX IF NOT EXISTS idx_chat_citation_note
    ON t_chat_citation (note_id)
    WHERE note_id IS NOT NULL;

-- ==================== Automatic audit timestamps ====================

DROP TRIGGER IF EXISTS trg_user_update_time ON t_user;
CREATE TRIGGER trg_user_update_time
BEFORE UPDATE ON t_user
FOR EACH ROW EXECUTE FUNCTION ng_touch_update_time();

DROP TRIGGER IF EXISTS trg_library_update_time ON t_library;
CREATE TRIGGER trg_library_update_time
BEFORE UPDATE ON t_library
FOR EACH ROW EXECUTE FUNCTION ng_touch_update_time();

DROP TRIGGER IF EXISTS trg_note_update_time ON t_note;
CREATE TRIGGER trg_note_update_time
BEFORE UPDATE ON t_note
FOR EACH ROW EXECUTE FUNCTION ng_touch_update_time();

DROP TRIGGER IF EXISTS trg_file_update_time ON t_file;
CREATE TRIGGER trg_file_update_time
BEFORE UPDATE ON t_file
FOR EACH ROW EXECUTE FUNCTION ng_touch_update_time();

DROP TRIGGER IF EXISTS trg_parse_task_update_time ON t_parse_task;
CREATE TRIGGER trg_parse_task_update_time
BEFORE UPDATE ON t_parse_task
FOR EACH ROW EXECUTE FUNCTION ng_touch_update_time();

DROP TRIGGER IF EXISTS trg_chat_session_update_time ON t_chat_session;
CREATE TRIGGER trg_chat_session_update_time
BEFORE UPDATE ON t_chat_session
FOR EACH ROW EXECUTE FUNCTION ng_touch_update_time();

DROP TRIGGER IF EXISTS trg_chat_message_update_time ON t_chat_message;
CREATE TRIGGER trg_chat_message_update_time
BEFORE UPDATE ON t_chat_message
FOR EACH ROW EXECUTE FUNCTION ng_touch_update_time();

COMMIT;
